### ISSUE TITLE
How can I change opacity property, when stars are disabled?

### ISSUE THREAD

**Issue by jecharmetout** [Saqib92/ion-rating-stars#3]

**Comment by Saqib92** [comment]
opacity property added when stars are disabled.

**Comment by jecharmetout** [comment]
Yes, I see,  but I need them to stay at opacity = 1 even if the stars are disable. Is there any way I can change this property?

**Comment by Saqib92** [comment]
Yes, please use latest version. 

When you do disable stars pass opacity as 1. 

```
<ion-rating-stars
  [disabled]="true"
  [opacity]="1"
  ></ion-rating-stars>
```

**Comment by jecharmetout** [comment]
Cool! Thank you!
